project:
  type: book
  output-dir: docs

book:
  title: " Proposed Kenai River Chinook Salmon Research"
  author: "Benjamin Meyer"
  date: today
  downloads: [docx]
  repo-url: https://github.com/benjamin-meyer-ak/kenai-chinook
  repo-actions: [source]
  chapters:
    - index.qmd
    #- intro.qmd
    #- summary.qmd
    - concept_note.qmd
    - references.qmd
format:
  html:
    toc: true
    toc-depth: 2
    theme:
      - cosmo
      - brand
    css: custom.css
  docx:
    number-sections: false
  #pdf:
  #  documentclass: scrreprt

filters:
  - docx-formatting.lua

bibliography: references.bib

editor: visual

